force-app/shared/config/objects/Picklist_Mapping__mdt/Picklist_Mapping__mdt.object-meta.xml
<CustomObject>
    <description>Dependent picklists</description>
    <label>Picklist Mapping</label>
    <pluralLabel>Picklist Mappings</pluralLabel>
</CustomObject>

force-app/shared/config/objects/Picklist_Mapping__mdt/fields/Object_API_Name__c.field-meta.xml
<CustomField>
    <fullName>Object_API_Name__c</fullName>
    <label>Object API Name</label>
    <length>99</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/shared/config/objects/Picklist_Mapping__mdt/fields/Picklist_API_Name__c.field-meta.xml
<CustomField>
    <fullName>Picklist_API_Name__c</fullName>
    <label>Picklist API Name</label>
    <length>99</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/shared/config/objects/Picklist_Mapping__mdt/fields/Picklist_Value__c.field-meta.xml
<CustomField>
    <fullName>Picklist_Value__c</fullName>
    <label>Picklist Value</label>
    <length>99</length>
    <type>Text</type>
</CustomField>

force-app/shared/custom/classes/COM_DependentPicklistService.cls
public class COM_DependentPicklistService extends COM_BaseComponentService{

    public List<PicklistValue> getPicklistValuesForCurrentUsersRegion(String objectApiName, String picklistApiName) {
        List<PicklistValue> picklistValues = new List<PicklistValue>();

        Profile userProfile = [
            SELECT Name
            FROM Profile
            WHERE Id = :UserInfo.getProfileId()
        ];

        List<Picklist_Mapping__mdt> picklists = [
            SELECT Picklist_Value__c
            FROM Picklist_Mapping__mdt
            WHERE  Picklist_API_Name__c = :picklistApiName AND Object_API_Name__c = :objectApiName
        ];

        for(Picklist_Mapping__mdt pm : picklists) {
            picklistValues.add(new PicklistValue(pm.Picklist_Value__c, pm.Picklist_Value__c));
        }

        return picklistValues;
    }

    public List<PicklistValue> getPicklistValuesByApiAndRegion(String objectApiName, String picklistApiName, String region) {
        List<PicklistValue> picklistValues = new List<PicklistValue>();

        List<Picklist_Mapping__mdt> picklists = [
                SELECT Picklist_Value__c
                FROM Picklist_Mapping__mdt
                WHERE Picklist_API_Name__c = :picklistApiName
                    AND Object_API_Name__c = :objectApiName
        ];

        for(Picklist_Mapping__mdt pm : picklists) {
            picklistValues.add(new PicklistValue(pm.Picklist_Value__c, pm.Picklist_Value__c));
        }

        return picklistValues;
    }
}