force-app/shared/config/objects/Application_Log__c/Application_Log__c.object-meta.xml
<CustomObject>
    <description>Object to hold custom exception messages</description>
    <label>Application Log</label>
    <nameField>
        <displayFormat>{YY}{MM}-{0}</displayFormat>
        <label>ApplicationLog Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Application Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/shared/config/objects/Application_Log__c/fields/Debug_Level__c.field-meta.xml
<CustomField>
    <fullName>Debug_Level__c</fullName>
    <description>Error, Info, Warning, Debug</description>
    <label>Debug Level</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Error</fullName>
                <default>true</default>
                <label>Error</label>
            </value>
            <value>
                <fullName>Info</fullName>
            </value>
            <value>
                <fullName>Warning</fullName>
            </value>
            <value>
                <fullName>Debug</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/shared/config/objects/Application_Log__c/fields/Integration_Payload__c.field-meta.xml
<CustomField>
    <fullName>Integration_Payload__c</fullName>
    <description>If log is integration related show xml payload</description>
    <label>Integration Payload</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/shared/config/objects/Application_Log__c/fields/Log_Code__c.field-meta.xml
<CustomField>
    <fullName>Log_Code__c</fullName>
    <description>Either the exception error code of custom org code for record</description>
    <label>Log Code</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/shared/config/objects/Application_Log__c/fields/Message__c.field-meta.xml
<CustomField>
    <fullName>Message__c</fullName>
    <description>Message to log</description>
    <label>Message</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/shared/config/objects/Application_Log__c/fields/Reference_Id__c.field-meta.xml
<CustomField>
    <fullName>Reference_Id__c</fullName>
    <description>The related record id</description>
    <label>Reference Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/shared/config/objects/Application_Log__c/fields/Reference_Info__c.field-meta.xml
<CustomField>
    <fullName>Reference_Info__c</fullName>
    <description>The related record info (e.g. Apex Batch Job Id, Contact etc)</description>
    <label>Reference Info</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/shared/config/objects/Application_Log__c/fields/Source__c.field-meta.xml
<CustomField>
    <fullName>Source__c</fullName>
    <description>The originating class (e.g. CustomerManagement)</description>
    <label>Source</label>
    <length>150</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/shared/config/objects/Application_Log__c/fields/Source_Function__c.field-meta.xml
<CustomField>
    <fullName>Source_Function__c</fullName>
    <description>The originating function in the class (e.g. UpdateDivision())</description>
    <label>Source Function</label>
    <length>200</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/shared/config/objects/Application_Log__c/fields/Stack_Trace__c.field-meta.xml
<CustomField>
    <fullName>Stack_Trace__c</fullName>
    <description>Raw exception stack trace for unhandled errors</description>
    <label>Stack Trace</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/shared/config/objects/Application_Log__c/fields/Timer__c.field-meta.xml
<CustomField>
    <fullName>Timer__c</fullName>
    <description>The time in milliseconds for the transaction</description>
    <label>Timer</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/shared/config/objects/System_Setting__c/System_Setting__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Object to hold what types of messages to log and how long to keep them for</description>
    <label>System Setting</label>
</CustomObject>

force-app/shared/custom/classes/COM_Logger.cls
public without sharing class COM_Logger {

    public final static String SIMPLIFIED_DESKTOP_REST_ENDPOINT_BASE = 'callout:SimplifiedDesktopBaseUrl';
    public final static String SIMPLIFIED_DESKTOP_REST_ENDPOINT_CREATE_LOG = '/services/data/v41.0/sobjects/Application_Log__c/';
    public final static String HEADER_ACCEPT = 'Accept';
    public final static String HEADER_CONTENT_TYPE = 'Content-Type';
    public final static String HEADER_VALUE_FORMAT_JSON = 'application/json;';
    public final static String HEADER_VALUE_METHOD = 'POST';

    public enum LogMode {MODE_DML, MODE_REST}

    private LogMode loggerMode;

    public COM_Logger() {
        this(LogMode.MODE_DML);
    }

    public COM_Logger(LogMode mode) {
        this.loggerMode = mode;
    }

    public void logMessage(String logLevel, String sourceClass, String sourceFunction, String logMessage, String payLoad, Exception ex, long timeTaken) {

        COM_ApplicationLogWrapper msg = new COM_ApplicationLogWrapper();

        msg.source = sourceClass;
        msg.logMessage = logMessage;
        msg.sourceFunction = sourceFunction;
        msg.referenceId = null;
        msg.referenceInfo = '';
        msg.payload = payLoad;
        msg.debugLevel = logLevel;
        msg.ex = ex;
        msg.Timer = timeTaken;

        logMessage(msg);
    }

    public void logMessage(String logLevel, String sourceClass, String sourceFunction, String referenceId, String referenceInfo, String logMessage, String payLoad, Exception ex, long timeTaken) {

        COM_ApplicationLogWrapper msg = new COM_ApplicationLogWrapper();

        msg.source = sourceClass;
        msg.logMessage = logMessage;
        msg.sourceFunction = sourceFunction;
        msg.referenceId = referenceId;
        msg.referenceInfo = referenceInfo;
        msg.payload = payLoad;
        msg.debugLevel = logLevel;
        msg.ex = ex;
        msg.Timer = timeTaken;

        logMessage(msg);
    }

    public void logMessage(COM_ApplicationLogWrapper appLog) {

        List<COM_ApplicationLogWrapper> appLogs = new List<COM_ApplicationLogWrapper>();
        appLogs.add (appLog);
        logMessage (appLogs);
    }

    public void logMessage(List<COM_ApplicationLogWrapper> appLogs) {

        List<Application_Log__c> insertAppLogs = new List<Application_Log__c>();

        for (COM_ApplicationLogWrapper appLog : appLogs) {

            Application_Log__c log = new Application_Log__c();

            log.Source__c = appLog.source;
            log.Source_Function__c = appLog.sourceFunction;
            log.Reference_Id__c = appLog.referenceId;
            log.Reference_Info__c = appLog.referenceInfo;
            log.Message__c = appLog.logMessage;
            log.Integration_Payload__c = appLog.payload;

            if (appLog.ex != null) {
                log.Stack_Trace__c = appLog.ex.getStackTraceString();
                log.Message__c = applog.ex.getMessage();
            }

            log.Debug_Level__c = appLog.debugLevel;
            log.Log_Code__c = appLog.logCode;
            log.Timer__c = appLog.timer;

            if (isDebugLevelEnabled(appLog.debugLevel)) {
                if(loggerMode == LogMode.MODE_DML){
                    insertAppLogs.add(log);
                }
                if(loggerMode == LogMode.MODE_REST){
                    logMessageByRest(log);
                }
            }
        }

        if (insertAppLogs.size() != 0) {
            insert insertAppLogs;
        }
    }

    private void logMessageByRest(Application_Log__c log){
        HttpRequest request = new HttpRequest();
        request.setEndpoint(SIMPLIFIED_DESKTOP_REST_ENDPOINT_BASE + SIMPLIFIED_DESKTOP_REST_ENDPOINT_CREATE_LOG);
        request.setHeader(HEADER_CONTENT_TYPE, HEADER_VALUE_FORMAT_JSON);
        request.setHeader(HEADER_ACCEPT, HEADER_VALUE_FORMAT_JSON);
        request.setMethod(HEADER_VALUE_METHOD);
        request.setBody(JSON.serialize(log));

        Http http = new Http();
        HttpResponse response = http.send(request);
    }

    private Boolean isDebugLevelEnabled(String debugLevel) {
        Set<String> settings = Schema.SObjectType.System_Setting__c.fields.getMap().keySet();
        return settings.contains(debugLevel.toLowerCase() + '__c')
                && System_Setting__c.getInstance().get(debugLevel + '__c') != null
                && Boolean.valueOf(System_Setting__c.getInstance().get(debugLevel + '__c'));
    }
}