force-app/shared/config/objects/Application_Log__c/Application_Log__c.object-meta.xml
<CustomObject>
    <description>Object to hold custom exception messages</description>
    <label>Application Log</label>
    <nameField>
        <displayFormat>{YY}{MM}-{0}</displayFormat>
        <label>ApplicationLog Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Application Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/shared/config/objects/Application_Log__c/fields/Debug_Level__c.field-meta.xml
<CustomField>
    <fullName>Debug_Level__c</fullName>
    <description>Error, Info, Warning, Debug</description>
    <label>Debug Level</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Error</fullName>
                <default>true</default>
                <label>Error</label>
            </value>
            <value>
                <fullName>Info</fullName>
            </value>
            <value>
                <fullName>Warning</fullName>
            </value>
            <value>
                <fullName>Debug</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/shared/config/objects/Application_Log__c/fields/Message__c.field-meta.xml
<CustomField>
    <fullName>Message__c</fullName>
    <description>Message to log</description>
    <label>Message</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/shared/config/objects/Application_Log__c/fields/Reference_Id__c.field-meta.xml
<CustomField>
    <fullName>Reference_Id__c</fullName>
    <description>The related record id</description>
    <label>Reference Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/shared/config/objects/Application_Log__c/fields/Reference_Info__c.field-meta.xml
<CustomField>
    <fullName>Reference_Info__c</fullName>
    <description>The related record info (e.g. Apex Batch Job Id, Contact etc)</description>
    <label>Reference Info</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/shared/config/objects/Application_Log__c/fields/Source__c.field-meta.xml
<CustomField>
    <fullName>Source__c</fullName>
    <description>The originating class (e.g. CustomerManagement)</description>
    <label>Source</label>
    <length>150</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/shared/config/objects/Application_Log__c/fields/Source_Function__c.field-meta.xml
<CustomField>
    <fullName>Source_Function__c</fullName>
    <description>The originating function in the class (e.g. UpdateDivision())</description>
    <label>Source Function</label>
    <length>200</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/shared/config/objects/System_Setting__c/System_Setting__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Object to hold what types of messages to log and how long to keep them for</description>
    <label>System Setting</label>
</CustomObject>

force-app/shared/config/objects/System_Setting__c/fields/Debug__c.field-meta.xml
<CustomField>
    <fullName>Debug__c</fullName>
    <defaultValue>true</defaultValue>
    <description>True- log debug messages in this org</description>
    <inlineHelpText>True- log debug messages in this org</inlineHelpText>
    <label>Debug</label>
    <type>Checkbox</type>
</CustomField>

force-app/shared/config/objects/System_Setting__c/fields/Error__c.field-meta.xml
<CustomField>
    <fullName>Error__c</fullName>
    <defaultValue>true</defaultValue>
    <description>True- log error messages in this org</description>
    <inlineHelpText>True- log error messages in this org</inlineHelpText>
    <label>Error</label>
    <type>Checkbox</type>
</CustomField>

force-app/shared/config/objects/System_Setting__c/fields/Info__c.field-meta.xml
<CustomField>
    <fullName>Info__c</fullName>
    <defaultValue>true</defaultValue>
    <description>True- log info messages in this org</description>
    <inlineHelpText>True- log info messages in this org</inlineHelpText>
    <label>Info</label>
    <type>Checkbox</type>
</CustomField>

force-app/shared/config/objects/System_Setting__c/fields/Log_Purge_Days__c.field-meta.xml
<CustomField>
    <fullName>Log_Purge_Days__c</fullName>
    <description>The number of days of logs to keep</description>
    <inlineHelpText>The number of days of logs to keep</inlineHelpText>
    <label>Log Purge (Days)</label>
    <precision>2</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/shared/custom/classes/COM_LoggerTest.cls
@IsTest
public class COM_LoggerTest {
    @IsTest
    private static void testLogging() {
        insertSettingForLogger(true, true, true, 1);
        COM_Logger logger = new COM_Logger();
        
        Test.startTest();
        logger.logMessage('Debug', 'COM_LoggerTest','testLogging', 'sampleMessage', null, null, null);
        Test.stopTest();

        List<Application_Log__c> existingLogs = [
            SELECT Source__c, Debug_Level__c, Source_Function__c, Message__c
            FROM Application_Log__c
        ];

        System.assertEquals(1, existingLogs.size());
        System.assertEquals('Debug', existingLogs[0].Debug_Level__c);
        System.assertEquals('COM_LoggerTest', existingLogs[0].Source__c);
        System.assertEquals('testLogging', existingLogs[0].Source_Function__c);
        System.assertEquals('sampleMessage', existingLogs[0].Message__c);
    }

    @IsTest
    private static void testLoggingWithReferences() {
        insertSettingForLogger(true, true, true, 1);
        COM_Logger logger = new COM_Logger();
        
        Test.startTest();
        logger.logMessage('Debug', 'COM_LoggerTest','testLogging', 'referenceId', 'referenceInfo', 'sampleMessage', null, null, null);
        Test.stopTest();

        List<Application_Log__c> existingLogs = [
            SELECT Source__c, Debug_Level__c, Source_Function__c, Message__c, Reference_Id__c, Reference_Info__c
            FROM Application_Log__c
        ];

        System.assertEquals(1, existingLogs.size());
        System.assertEquals('Debug', existingLogs[0].Debug_Level__c);
        System.assertEquals('COM_LoggerTest', existingLogs[0].Source__c);
        System.assertEquals('testLogging', existingLogs[0].Source_Function__c);
        System.assertEquals('sampleMessage', existingLogs[0].Message__c);
        System.assertEquals('referenceId', existingLogs[0].Reference_Id__c);
        System.assertEquals('referenceInfo', existingLogs[0].Reference_Info__c);
    }

    private static void insertSettingForLogger(Boolean debugFlag, Boolean errorFlag, Boolean infoFlag, Integer logPurgeDays) {
        System_Setting__c setting = new System_Setting__c(Debug__c = debugFlag, Error__c = errorFlag, Info__c = infoFlag, Log_Purge_Days__c = logPurgeDays);
        insert setting;
    }
}